### PR TITLE
Fix #112: Allow image types that OS recognizes

### LINKED ISSUE #112: Use `mimetypes` to get a list of image file extensions that the OS recognizes
The app is currently using a manually constructed list of common image file extensions to pick out image files. A more robust solution would be to use `mimetypes` a la https://miro.medium.com/max/1896/1*NeFJDWHCtGUdNgjIVcmE6w.png

### PR DESCRIPTION
**Pull request by rahulgurnani**
Reference: #112

In this change, allowed image types are read from mimetypes module.

Pull Request Checklist
 - [x] Pull request includes a description of the change and the reason behind it.
 - [x] Pull request [uses keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to close relevant [issues](https://github.com/uptake/autofocus/issues).
 - [x] Pull request includes unit tests for any new functionality.
 - [x] README and docs have been updated.
 - [x] `./.ci/local_checks.sh` passes locally. (The app must be running. See `README.md` for instructions.)

Maintainer's responsibilities:
- [ ] `_version.py` has been updated.
- [ ] `CHANGELOG.md` has been updated.
- [ ] Updated app container has been pushed, if relevant, with current version number.
- [ ] App container version number has been updated in README.

### CODE REVIEW

**Comment by gsganden** [comment]
Thanks for the PR! We need to apply `black` to format the code and confirm that the other checks pass. You can make those changes, or I will make a PR to your fork when I get a chance.

**Comment by gsganden** [comment]
Cool. I just need to take care of the "maintainer's responsibilities." I think the simplest approach might be for you to resubmit this PR from your fork into a branch here so that I can merge it, make those changes, and then merge it into master. If that's too much trouble then I can make a PR on your fork when I get a chance.

**Comment by rahulgurnani** [comment]
It's fine, I will raise another PR. I am going to decline this PR.

**Comment by rahulgurnani** [comment]
Which branch should I raise the PR to?

**Comment by gsganden** [comment]
Cool. Is it possible for you to open a new branch with some descriptive name, or do I need to do that?

**Comment by rahulgurnani** [comment]
I don't have permission to create a new branch. Can you please do that?

**Comment by gsganden** [comment]
Yes, I just pushed a branch called `mimetypes`. Unfortunately it might be tricky to merge your change in because they have separate histories. The simplest solution might be just to pull that branch down and redo your change on it.

Sorry for the inconvenience!

**Pull request closed without merging**
