### PR TITLE
Automate image build

### LINKED ISSUE #111: Automate container push with Travis
Right now I have to push new versions of the app to Dockerhub manually. Pushing them automatically as part of Travis builds when merging into master would be more reliable.

### PR DESCRIPTION
**Pull request by davidwilby**
Resolves #111 (as discussed, using github actions)

Work in progress to build image and push to dockerhub on pushes to `master`.

To do:
 - [x] check with  `./.ci/local_checks.sh` locally
 - [ ] rebase onto `dev`?

Changes to make before/on merging:
 - [x] set correct dockerhub user (gsganden?) and image name.
 - [x] add AWS credentials to repo secrets (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`)
 - [x] add Dockerhub username and token  to repo secrets (`DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`)

Pull Request Checklist
 - [x] Pull request has been made against `dev` branch.
 - [x] Pull request includes a description of the change and the reason behind it.
 - [x] Pull request [uses keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to close relevant [issues](https://github.com/uptake/autofocus/issues).
 - [ ] Pull request includes unit tests for any new functionality.
 - [ ] README and docs have been updated.
 - [x] `./.ci/local_checks.sh` passes locally. (The app must be running. See `README.md` for instructions.)

Maintainer's responsibilities:
- [ ] `_version.py` has been updated.
- [ ] `CHANGELOG.md` has been updated.
- [ ] Updated app container has been pushed with current version number.
- [ ] App container version number has been updated everywhere in README.

### CODE REVIEW

**Comment by davidwilby** [comment]
This gets most of the job done via  `.github/workflows/automate-image-build-push.yml` however there is an error produced on building and running the container:

```
  File "/image_api/app/app.py", line 7, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/opt/conda/lib/python3.7/site-packages/werkzeug/__init__.py)
```
which seems to have been introduced since the last time the image was built, via a problem in the package `flask-uploads` described here: https://github.com/maxcountryman/flask-uploads/pull/28

logged during the build as:
```
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
```

**Comment by gsganden** [comment]
Got it, thanks!

**Comment by gsganden** [comment]
I think the changes GitHub is showing in autofocus/build_dataset/helpers.py and autofocus/predict/app/app.py were already in `master` but not in `dev`. Is that your understanding? If so, my bad.

**Review by gsganden — APPROVED** [review]
Looks good, thanks!

**Review by gsganden — CHANGES_REQUESTED** [review]
Marking as "Requested changes" until the build passes.

**Comment by davidwilby** [comment]
Yes, the majority of chose changes (except those in 77481c7 & 5f7ef4a) are from the `master` branch. However, the PR is made against `dev` as per the contribution instructions, but this branch `davidwilby:automate-image-build` is branched from `master`. So to make the changes relative to `dev` clearer, we could rebase onto `dev`? If not, merging this PR will merge all the changes on `master` into `dev`. Up to you.

Regarding [the failing checks](https://travis-ci.org/github/uptake/autofocus/jobs/737471676), it looks like this is to do with a version incompatibility in `black` - https://github.com/psf/black/issues/1666 which comes down to python <3.6.2 being incompatible with a type hint import of `typing.NoReturn` in `black 20.8b1` - so could either up the python version that the checks run on, or bring the black version in pip down.

In 7e5aaae I've tried bumping it up to 3.6.12, though since 3.9 is now released, you should maybe consider using 3.8 or higher.

**Comment by gsganden** [comment]
I'm OK with merging. Thank you!

**Pull request merged**
