### PR TITLE
Pretty up readme

### PR DESCRIPTION
**Pull request by gsganden**
Fixes Travis badge after we dropped "opensource" from the organization name. Adds a few fun images to the README.

Pull Request Checklist
 - [X] Pull request includes a description of the change and the reason behind it.
 - [X] Pull request [uses keywords to close relevant issues](https://help.github.com/en/articles/closing-issues-using-keywords).
 - [X] Pull request includes unit tests for any new functionality.
 - [X] README and docs have been updated.
 - [X] `./.ci/test.sh` passes locally.

Maintainer's responsibilities:
- [X] `_version.py` has been updated.
- [X] `CHANGELOG.md` has been updated.

### CODE REVIEW

**Comment by gsganden** [comment]
Thanks, @jayqi! Could you please "approve" explicitly so that GitHub will let me merge?

**Comment by gsganden** [comment]
Nm, apparently I need an approval from someone with write access.

**Comment by gsganden** [comment]
@jameslamb could you please rubber-stamp this PR? Is there anyone else who has write access?

**Comment by jayqi** [comment]
IMO @gsganden, given that you have an approval from me, that satisfies both the spirit and practical value of the thing, so you should use your admin power for this repo to force-merge the PR.

**Comment by gsganden** [comment]
I agree, but I don't know how to get it to let me do that: `git push --force origin master` gives "error: At least 1 approving review is required by reviewers with write access."

**Comment by gsganden** [comment]
I found a workaround: temporarily turn off the relevant branch protection.

**Comment by jayqi** [comment]
@gsganden in another repo I have, I have the "Include administrators" box disabled. This gives me an option to override the branch protect that is still pretty explicitly called out and doesn't feel that dangerous.

Screen Shot 2019-06-13 at 9 04 14 PM

(per item 10 here: https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests)

**Pull request merged**
